var settings = {
  dots: false,
  arrows: false,
  speed: 500,

  infinite: true,

  slidesToShow: 3,
  slidesToScroll: 1,
  responsive: [
    {
      breakpoint: 1921,
      settings: {
        slidesToShow: 3,
        slidesToScroll: 1,
        centerMode: false,
      },
    },

    {
      breakpoint: 1280,
      settings: {
        slidesToShow: 3,
        speed: 500,
        slidesToScroll: 1,
        infinite: true,
        dots: false,
        arrows: false,
      },
    },
    {
      breakpoint: 1023,
      settings: {
        slidesToShow: 2,
        speed: 500,
        slidesToScroll: 1,
        infinite: true,
        dots: true,
        arrows: false,
      },
    },
    {
      breakpoint: 860,
      settings: {
        slidesToShow: 2,
        slidesToScroll: 1,
        initialSlide: 2,
        centerMode: true,
        centerPadding: "50px",
        arrows: false,
        dots: true,
      },
    },
    {
      breakpoint: 768,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        initialSlide: 2,
        centerMode: true,
        centerPadding: "180px",
        arrows: false,
        dots: true,
      },
    },
    {
      breakpoint: 655,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        initialSlide: 2,
        centerMode: true,
        centerPadding: "160px",
        arrows: false,
        dots: true,
      },
    },
    {
      breakpoint: 620,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        initialSlide: 2,
        centerMode: true,
        centerPadding: "140px",
        arrows: false,
        dots: true,
      },
    },
    {
      breakpoint: 587,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        initialSlide: 2,
        centerMode: true,
        centerPadding: "130px",
        arrows: false,
        dots: true,
      },
    },
    {
      breakpoint: 550,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        initialSlide: 2,
        centerMode: true,
        centerPadding: "100px",
        arrows: false,
        dots: true,
      },
    },
    {
      breakpoint: 500,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        initialSlide: 2,
        centerMode: true,
        centerPadding: "75px",
        arrows: false,
        dots: true,
      },
    },
    {
      breakpoint: 450,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        initialSlide: 2,
        centerMode: true,
        centerPadding: "60px",
        arrows: false,
        dots: true,
      },
    },
    {
      breakpoint: 415,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        initialSlide: 2,
        centerMode: true,
        centerPadding: "50px",
        arrows: false,
        dots: true,
      },
    },
    {
      breakpoint: 390,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        initialSlide: 2,
        centerMode: true,
        centerPadding: "40px",
        arrows: false,
        dots: true,
      },
    },
    {
      breakpoint: 370,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        initialSlide: 2,
        centerMode: true,
        centerPadding: "30px",
        arrows: false,
        dots: true,
      },
    },
    {
      breakpoint: 350,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        initialSlide: 2,
        centerMode: true,
        centerPadding: "20px",
        arrows: false,
        dots: true,
      },
    },
    {
      breakpoint: 330,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        initialSlide: 2,
        centerMode: true,
        centerPadding: "10px",
        arrows: false,
        dots: true,
      },
    },
  ],
};
export default settings;
