var winnerSldierSettings = {
  dots: true,
  arrows: true,
  speed: 500,
  infinite: true,
  slidesToShow: 3,
  slidesToScroll: 1,
  initialSlide: 1,
  responsive: [
    {
      breakpoint: 1400,
      settings: {
        slidesToShow: 3,
        slidesToScroll: 3,
        infinite: true,
        dots: true,
        arrows: false,
      },
    },

    {
      breakpoint: 1024,
      settings: {
        slidesToShow: 3,
        slidesToScroll: 2,
        infinite: true,
        dots: true,
        arrows: false,
      },
    },
    {
      breakpoint: 763,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        initialSlide: 2,
        centerMode: true,
        centerPadding: "250px",
        arrows: false,
        dots: true,
      },
    },
    {
      breakpoint: 725,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        initialSlide: 2,
        centerMode: true,
        centerPadding: "240px",
        arrows: false,
        dots: true,
      },
    },
    {
      breakpoint: 705,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        initialSlide: 2,
        centerMode: true,
        centerPadding: "230px",
        arrows: false,
        dots: true,
      },
    },
    {
      breakpoint: 680,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        initialSlide: 2,
        centerMode: true,
        centerPadding: "210px",
        arrows: false,
        dots: true,
      },
    },
    {
      breakpoint: 655,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        initialSlide: 2,
        centerMode: true,
        centerPadding: "190px",
        arrows: false,
        dots: true,
      },
    },
    {
      breakpoint: 595,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        initialSlide: 2,
        centerMode: true,
        centerPadding: "160px",
        arrows: false,
        dots: true,
      },
    },
    {
      breakpoint: 535,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        initialSlide: 2,
        centerMode: true,
        centerPadding: "130px",
        arrows: false,
        dots: true,
      },
    },
    {
      breakpoint: 475,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        initialSlide: 2,
        centerMode: true,
        centerPadding: "100px",
        arrows: false,
        dots: true,
      },
    },
    {
      breakpoint: 415,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        initialSlide: 2,
        centerMode: true,
        centerPadding: "70px",
        arrows: false,
        dots: true,
      },
    },
    {
      breakpoint: 350,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        initialSlide: 2,
        centerMode: true,
        centerPadding: "50px",
        arrows: false,
        dots: true,
      },
    },
    {
      breakpoint: 310,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        initialSlide: 2,
        centerMode: true,
        centerPadding: "30px",
        arrows: false,
        dots: true,
      },
    },
  ],
};
export default winnerSldierSettings;
